Revert "[WIP] workflow: disable draft, leave prerelease true"
Draft is required, otherwise this error happens:

   Error: ⚠️ GitHub Releases requires a tag

This reverts commit 798bb4dba0bf37f5c0bfefe745b25fcae0e8a4b8.